# Generated by Django 4.2.7 on 2025-07-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='date_validation',
            field=models.DateTimeField(blank=True, help_text='Date de validation/rejet', null=True),
        ),
        migrations.AddField(
            model_name='materiel',
            name='statut_validation',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', help_text='Statut de validation du matériel', max_length=20),
        ),
    ]
