# Generated by Django 4.2.7 on 2025-07-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='commentaire_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
