# Generated by Django 4.2.7 on 2025-07-27 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0003_materiel_date_ajout_materiel_reference_materiel_site'),
        ('demandes', '0003_demande_commentaire_admin_demande_date_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='description',
            field=models.TextField(default='Demande créée automatiquement', help_text='Description détaillée de la demande'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demande',
            name='site',
            field=models.ForeignKey(default=1, help_text='Site de livraison', on_delete=django.db.models.deletion.CASCADE, to='materiel.site'),
            preserve_default=False,
        ),
    ]
